version: '3.8'
services:
  solace:
    container_name: solace
    hostname: solace
    image: solace/solace-pubsub-standard:latest
    volumes:
      # Data mount
      - data:/var/lib/solace
      # Configuration script
      - ./conf/solace/solace.sh:/solace.sh
      - ./conf/solace/solace-start.sh:/solace-start.sh
      # Mount the client certificate for client certificate authentication
      - ./conf/solace/solace-client.pem:/usr/sw/jail/certs/client.pem
      - ./conf/solace/server_combined.pem:/usr/sw/jail/certs/server.pem
      - ./conf/solace/solace_config.cli:/usr/sw/jail/cliscripts/solace_config.cli
      # Logs
      - logs:/usr/sw/jail/logs
    command: sh /solace-start.sh
    shm_size: 1g
    ulimits:
      core: -1
      nofile:
        soft: 2448
        hard: 1048576
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 1
    ports:
      #Port Mappings:  With the exception of SMF, ports are mapped straight
      #through from host to container.  This may result in port collisions on
      #commonly used ports that will cause failure of the container to start.
      #Web transport
      - '8008:8008'
      #Web transport over TLS
      - '1443:1443'
      #SEMP over TLS
      - '1943:1943'
      #MQTT Default VPN
      - '1883:1883'
      #AMQP Default VPN over TLS
      - '5671:5671'
      #AMQP Default VPN
      - '5672:5672'
      #MQTT Default VPN over WebSockets
      - '8000:8000'
      #MQTT Default VPN over WebSockets / TLS
      - '8443:8443'
      #MQTT Default VPN over TLS
      - '8883:8883'
      #SEMP / PubSub+ Manager
      - '8080:8080'
      #REST Default VPN
      #- '9000:9000'
      #REST Default VPN over TLS
      - '9443:9443'
      #SMF
      - '55554:55555'
      #SMF Compressed
      - '55003:55003'
      #SMF over TLS
      - '55443:55443'
      #SSH connection to CLI
      - '2222:2222'
      # Kafka Bridge
      - '9092:9092'
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin
      - system_scaling_maxconnectioncount=100
      - routername=solace
      - messagespool_maxspoolusage=5223
    healthcheck:
      test: [ "CMD", "test", "-f", "/tmp/solace_configured.ready" ]
      interval: 10s
      timeout: 5s
      retries: 300
      start_period: 5m
volumes:
  data:
  logs: